server {
    listen 80;
    server_name _;
    root /usr/share/nginx/html;
    index index.html;

    # Compressão gzip
    gzip on;
    gzip_types text/css text/javascript application/javascript text/html;

    # Todas as rotas vão para o index.html (React Router)
    location / {
        try_files $uri $uri/ /index.html;
    }

    # Cache para assets estáticos
    location ~* \.(jpg|jpeg|png|gif|ico|css|js|svg|woff|woff2)$ {
        expires 1y;
        add_header Cache-Control "public, immutable";
    }
}